# Generated by Django 4.1.2 on 2023-03-12 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoopInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='loop1', max_length=50)),
                ('loop_id', models.IntegerField(default=0)),
                ('x1', models.IntegerField(default=900)),
                ('y1', models.IntegerField(default=600)),
                ('x2', models.IntegerField(default=900)),
                ('y2', models.IntegerField(default=300)),
                ('x3', models.IntegerField(default=400)),
                ('y3', models.IntegerField(default=300)),
                ('x4', models.IntegerField(default=400)),
                ('y4', models.IntegerField(default=600)),
                ('orientation', models.CharField(max_length=50)),
                ('x', models.IntegerField(default=20)),
                ('y', models.CharField(default='20', max_length=50)),
            ],
        ),
    ]
