# Generated by Django 4.1.3 on 2023-03-15 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='loop',
            field=models.FileField(default='a', upload_to='loop/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='input_vdo',
            field=models.FileField(upload_to='vdo_input/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='output_vdo',
            field=models.FileField(null=True, upload_to='output/'),
        ),
    ]
