# Generated by Django 4.1.3 on 2023-03-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_loop_alter_task_input_vdo_alter_task_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='report',
            field=models.FileField(null=True, upload_to='report_output/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='output_vdo',
            field=models.FileField(null=True, upload_to='vdo_output/'),
        ),
    ]
