# Generated by Django 4.1.7 on 2023-04-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='already_read',
            field=models.BooleanField(default=False),
        ),
    ]
