# Generated by Django 4.1.2 on 2023-04-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_notification_already_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='latitude',
            field=models.FloatField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='longitude',
            field=models.FloatField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='input_vdo',
            field=models.FileField(blank=True, null=True, upload_to='vdo_input/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='loop',
            field=models.FileField(blank=True, null=True, upload_to='loop/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
