# Generated by Django 4.1.3 on 2023-03-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_alter_task_created_at_alter_task_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='preset',
            field=models.BooleanField(default=False),
        ),
    ]
