# Generated by Django 4.1.3 on 2023-03-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_task_preset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='output_vdo',
            field=models.FileField(blank=True, null=True, upload_to='vdo_output/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='report_output/'),
        ),
    ]
