# Generated by Django 4.1.2 on 2023-03-12 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_scheduledtask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scheduler',
        ),
    ]
