# Generated by Django 4.1.2 on 2023-04-19 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0005_task_latitude_task_longitude_alter_task_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=64)),
                ('note', models.CharField(max_length=64)),
                ('battery', models.IntegerField()),
                ('schedule', models.DateTimeField(max_length=64)),
                ('height', models.FloatField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=64)),
                ('latitude', models.FloatField(max_length=64)),
                ('longitude', models.FloatField(max_length=64)),
                ('temp', models.FloatField(max_length=64)),
                ('humidity', models.IntegerField()),
                ('wind_speed', models.FloatField(max_length=64)),
                ('weather_report', models.CharField(max_length=64)),
                ('clouds', models.IntegerField()),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.task')),
            ],
        ),
    ]
